version: '2'
services:
  dev:
    image: node:9.6.1
    command: bash
    working_dir: /app
    user: '$NODE_USER'
    volumes: 
        - .:/app

  server:
    image: node:9.5
    command: node_modules/.bin/nodemon server/index.js
    working_dir: /app
    volumes: 
        - .:/app
    ports:
        - '8000:80'

  mongo:
    image: mongo:3.6
    volumes:
        - ./.data:/data/db

  index:
    image: node:9.5
    command: node index.js
    user: '1000:1000'
    working_dir: /app
    volumes: 
    - .:/app