const FINISH_DRAW = `DRAW`
const CELL_EMPTY = 0
const PLAYER_A = 1
const PLAYER_B = 2
const FINISH_ONGOING = 10
const FINISH_WIN_A = 11
const FINISH_WIN_B = 12

module.exports = {
    CELL_EMPTY,
    PLAYER_A,
    PLAYER_B,
    FINISH_ONGOING,
    FINISH_WIN_A,
    FINISH_WIN_B,
    FINISH_DRAW,
    getFinish,
    createEmptyBoard,
}

function createEmptyBoard() {
    return [
        [CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY],
        [CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY],
        [CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY],
        [CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY],
        [CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY],
        [CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY, CELL_EMPTY],
    ]
}

function getFinish() {

}